module.exports = {
  NODE_ENV: '"production"',
  BASE_URL: process.env.VUE_APP_BASE_URL,
  APP_URL: process.env.AVUE_APP_PP_URL,
  IPINFO_TOKEN: process.env.VUE_APP_IPINFO_TOKEN,
  SERVER_ENDPOINT_OAUTH: process.env.VUE_APP_SERVER_ENDPOINT_OAUTH,
  TIKTOK_CLIENT_KEY: process.env.VUE_APP_TIKTOK_CLIENT_KEY,
  TIKTOK_REDIRECT_URI: process.env.VUE_APP_TIKTOK_REDIRECT_URI,
  TALKIFY_KEY: process.env.VUE_APP_TALKIFY_KEY,
  TOKEN_VALIDATE_ENDPOINT: process.env.VUE_APP_TOKEN_VALIDATE_ENDPOINT,
}
