module.exports = {
    NODE_ENV: '"production"',
    SERVER_ENDPOINT_OAUTH: process.env.VUE_SERVER_ENDPOINT_OAUTH,
    TIKTOK_CLIENT_KEY: process.env.VUE_TIKTOK_CLIENT_KEY,
    TIKTOK_REDIRECT_URI: process.env.VUE_TIKTOK_REDIRECT_URI,
    SECRET_ACCESS_KEY: process.env.VUE_APP_AWS_SECRET_ACCESS_KEY,
    ACCESS_KEY_ID: process.env.VUE_APP_AWS_ACCESS_KEY,
    AWS_BUCKET: process.env.VUE_APP_AWS_BUCKET,
    AWS_REGION: process.env.VUE_APP_AWS_REGION,
    BASE_URL: process.env.VUE_APP_API,
    APP_URL: process.env.VUE_APP_APP_URL,
    IPINFO_TOKEN: process.env.VUE_APP_IPINFO_TOKEN,
    TALKIFY_KEY: process.env.VUE_APP_TALKIFY_KEY,
    TOKEN_VALIDATE_ENDPOINT: process.env.VUE_APP_TOKEN_VALIDATE_ENDPOINT,
    SECRET_ACCESS_KEY: process.env.VUE_APP_AWS_SECRET_ACCESS_KEY,
    ACCESS_KEY_ID: process.env.VUE_APP_AWS_ACCESS_KEY,
    AWS_BUCKET: process.env.VUE_APP_AWS_BUCKET,
    AWS_REGION: process.env.VUE_APP_AWS_REGION
}
